export const TIMING = {
    ENGINE_STALL_TIMEOUT: 2000,
    DEBUG_LOG_SAMPLE_RATE_RARE: 0.016, // Approx 1/60 frames
    RECORDING_WARMUP: 1000,
    RECORDING_LOG_INTERVAL: 30,
    UI_UPDATE_THROTTLE: 66,
    ACTION_EMIT_DEBOUNCE: 200,
};

export const SMOOTHING = {
    VRM_BONE_SLERP: 0.8,
    SHOULDER_Z_DAMPEN: 0.5,
    LANDMARK_FILTER: 0.5,
};

export const COORDINATES = {
    VRM_HIP_Y_OFFSET: 1.0,
};
